### ISSUE TITLE
[CITS_Geospatial_v3.pdf] proprietary data

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#11]
p.11 "proprietary" is not a format but an ownership type

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/85dc9ccf-bb52-4fd7-bb86-8398f0e528ae)

**Comment by GregorZavrsnik** [comment]
This is a typo, the word "formats" is missing. It should say "Proprietary data formats". The typo will be corrected in the document.
