### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] Use of the terms "feature" 

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#15]
p.9 The term "feature" is usually restricted to vector data. Raster datasets don't model objects 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/529f1544-1e5c-494b-a01e-326bfc16292e)

**Comment by GregorZavrsnik** [comment]
The description in the guidelines was changed to:
"_An object in the real world can be represented as a feature with its geometry represented as a vector (lines represented by multiple sets of coordinates) or as a raster object (a set of pixels with the same values within a larger image). In geospatial data, this geometry always has coordinates based on a Geographical Coordinate Reference System._"
