### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] More geometry types 

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#16]
p.9 The ISO/IEC 13249-3 SQL/MM Spatial extends the Simple Features data model with  "Circularstring", "CompoundCurve", "CurvePolygon", "PolyhedralSurface", 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/f6a867f1-2e82-4d7a-b2ee-7c4d6aa685bc)

**Comment by GregorZavrsnik** [comment]
The text in the guiudeline will be changed to:
"Geospatial vector Feature datasets can have different types of geometries (point, line, polygon, multipoint, multiline, multipolygon, and different types of curves and surfaces). Types may vary, based on standards and implementations.
