### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] Use the term metadata

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#17]
p. 10 I would expect the word "metadata" somewhere here.

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/df5a9b7b-ccfb-4373-9b8b-b590cc96f7fa)

**Comment by GregorZavrsnik** [comment]
The term Feature Catalogue is commonly used without the word "metadata" as it is described in the ISO 19110 standard. Later in the document, it is described, that the Feature Catalogue is a part of documentation about a dataset and it is therefore technically metadata itself, but that shouldn't be the reason to call it medatata.
