### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] machine-readable PDF

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#22]
p. 21 I don't think machine-readable and PDF go together

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/ca98faed-2b53-4689-94b6-2293d46d035a)

**Comment by GregorZavrsnik** [comment]
The term "machine-readable documentation" was changed to "documentation in digital form"
