### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] Add topology rules

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#23]
p. 21 Would the behaviour section be the right place to talk about topology rules that should be applied to the data? e.g. polygons representing states should not overlap 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/cc28c687-23cd-4736-8d80-57e749261158)

**Comment by GregorZavrsnik** [comment]
Yes, this is exactly where the Topology rules should be documented, especially if the topology is validated on the application level. However, the rules themselves could also be incorporated in the data model of a certain format, if supported.
