### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] Consistency of Fig. 2 and text

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#25]
p. 22 In Fig. 2 the directory is called "GML321"

And I don't see a ETRS3794.prj file in Fig 2

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/4eb29a4c-c6bc-4952-a567-fc90237e54ec)

**Comment by GregorZavrsnik** [comment]
Corrected
