### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] GEO_15 Rationale - gridfiles

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#28]
p. 34 If a specific coordinate transformation should be applied to the dataset, the respective transformation grid (e.g. NTv2 .GSB file) should be included as well

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/d010704f-1a01-4c3d-ad0e-741e2b5bbe98)

**Comment by anitagraser** [comment]
“Transformation grids improve accuracy when you are performing datum transformations.” https://pyproj4.github.io/pyproj/dev/transformation_grids.html
“Some countries, like the United States and Canada, use a grid-based geographic (datum) transformation method. A grid contains the differences (often in seconds) between two geographic coordinate systems. Grid-based methods can be very accurate because a grid can model small changes in the fit between the two geographic coordinate systems (GCS).” https://help.arcgis.com/en/geodatabase/10.0/sdk/arcsde/concepts/geometry/coordref/coordsys/geographic/usinggrid_gt.htm
The first time I learned about them was in the context of Australia:  https://www.icsm.gov.au/datum/gda-transformation-products-and-tools/transformation-grids

“The NTv2 (National Transformation version 2) is a standard binary grid shift (.GSB) file format. It can transform coordinates between the NAD27 and NAD83 geodetic reference systems for example. The transformation is bidimensional (2D), or horizontal, and does not require heights.” https://en.wikipedia.org/wiki/NTv2
“The heart of the NTv2 Grid Shift transformation is the binary format grid shift data file which specifies grid shift values and accuracy indicators on regular grids of latitude and longitude, determined by distortion modelling of large numbers of known points scattered across the country to compensate for distortions between the datums in smaller areas. A number of grids of varying density may be contained within an NTv2 file, where larger intervals are typically used for broad expanses over less-populated areas, and smaller intervals in areas of greater human activity and interest.” https://www.geoida.com/WebHelp/HTML/NTv2%20Grid%20Shift%20Transformation.htm

**Comment by GregorZavrsnik** [comment]
This issue is solved in the GEO_39 requirement, where the many different types of transformation parameters can be stored, as well as the forementioned 2D transformation grids.
