### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] GEO_19 Rationale - composite keys

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#29]
p. 37 Does this support composite unique keys? e.g. in GPS tracks, the unique key may be object ID + timestamp

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/c80677ab-3f6c-4d45-933f-a068ce6d50bf)

**Comment by GregorZavrsnik** [comment]
Yes, it does
