### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] GEO_32 Rationale - Styling / QML

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#33]
p. 58 add a note here that QGIS qml style files should be preserved rather than just a screenshot

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/373e8753-eb17-42ce-91f1-049c78ca2091)

**Comment by GregorZavrsnik** [comment]
The following sentence was added to the text after the mention of the Figure 9 Image:
"In QGIS, for example, such rendering information can be stored in a machine-readable *.qml file."
