### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] GEO_33 Rationale - Styling / SLD

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#34]
p. 60 It should be noted, however, that the capabilities of SLD are rather limited. Therefore, many cartographic styling details cannot be adequately represented in SLD.

QGIS QML and ESRI layer LYR are much more powerful but not standardized.

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/3f56af40-e554-4414-a13b-9b77b323a5f0)

**Comment by GregorZavrsnik** [comment]
The following content was added to the example text:
"It must be noted, however, that the SLD standard is rather limited. Therefore, many cartographic styling details cannot be adequately represented in SLD, as opposed to, for example QML  (from QGIS) and LYR  (ESRI layer file) are much more powerful but not standardized."

And Links to QML and LYR descriptions were added:
- QGIS QML Style file (https://docs.qgis.org/3.34/en/docs/user_manual/appendices/qgis_file_formats.html#qml-the-qgis-style-file-format)
- esri LYR style file (https://www.loc.gov/preservation/digital/formats/fdd/fdd000626.shtml )
