### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] GEO_37 Rationale - source code

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#36]
p. 64 Also explicitly mention source code of algorithm implementations in examples

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/3fdbb997-ec5a-4ea5-81d6-25374a6e6cbb)

**Comment by GregorZavrsnik** [comment]
The Example text was changed to:

Standardised machine-readable examples would include any type of source code ( scripts, sql queries, SPARQL queries, pyhon code, c++ code, etc.) that were used to produce an information product using geospatial data.
