### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] Inspire Tools

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#39]
p. 95 It may be worthwhile to add more information on INSPIRE tools here, e.g. https://wiki.osgeo.org/wiki/INSPIRE_tools_inventory
"QGIS can be used to consume INSPIRE compliant view and download services. The QGIS plugin ‘GML Application Schema Toolbox’ makes use of the GMLAS driver for GDAL and aims to develop tools to manipulate complex features in a GIS desktop application. On the related GitHub page ‘Consumption and use of GML complex features like INSPIRE harmonised data (vector), GeoSciML within QGIS’, specific INSPIRE use cases are described and illustrated."

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/b726d4da-1530-4141-9af8-2ab17b4a3549)

**Comment by GregorZavrsnik** [comment]
Additional information was added to the tools section based on your recomentdation:
- Extended QGIS description with most of the suggested text from above
- Hale>>Studio description and link
- Special section describing OSGeo.org INSPIRE tools inventory
