### ISSUE TITLE
Incomplete sentence in Purpose

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#43]
The last sentence in section 1.1 Purpose appears incomplete: 

> To reproduce digital products in the forms of different types of maps (...), lists, tables, or new geospatial records in the form
of vector, raster, or any other kind of geospatial record.

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/1b89da71-5aa5-4ab0-9d28-1b2e0603f0d6)

**Comment by GregorZavrsnik** [comment]
The following text was added to this paragraph:
"The elements of the recipe consist of the context in which data was created and used, different types of rendering rules and configurations, a definition of how data was structured and of course the behavior, the logic on how it was manipulated to produce the digital information product."
