### ISSUE TITLE
Unclear sentence in DB Section

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#44]
The meaning of this sentence in section 2.2.2.2 is not clear:

> When geospatial records are loaded into databases, they can change their form and extent.

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/f200f75f-0180-45ef-bf58-892cae059a72)

**Comment by GregorZavrsnik** [comment]
The market text in the issue image was changed to:
"When geospatial datasets are loaded into databases, they can change their format and extent. Data can be split in smaller elements and column datatypes might be different than in original format."
