### ISSUE TITLE
Broken links in 2.4 Recommended reading list

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#46]
In 2.4

> More documentation on the preservation of geospatial data http://geopreservation.org/

~~http://geopreservation.org seems to be down: https://downforeveryoneorjustme.com/geopreservation.org?proto=http~~

Update 2023-12-14: The page is accessible again. However, the content seems rather dated (with the most recent updates from 2014) and many of the links on the website are broken.

**Comment by anitagraser** [comment]
I'm also experiencing issues with https://osgis.org/2020/06/the-ultimate-list-of-gis-formats-and-geospatial-file-extensions/

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/2d172347-c900-42c2-bf7c-67b5643c22b7)

**Comment by anitagraser** [comment]
And http://geopreservation.org/policies.do

https://downforeveryoneorjustme.com/geopreservation.org?proto=http

**Comment by anitagraser** [comment]
I've had no luck with trying to archive geopreservation.org so far: https://web.archive.org/web/20231120124452/http://geopreservation.org/index.jsp;jsessionid=4790E2E4E0B4ED49F572B570370BF01C

**Comment by anitagraser** [comment]
It may also be of interest to reference other existing guidelines, see. #59

**Comment by GregorZavrsnik** [comment]
All the links in this section were checked. The geopreservation.org webpages only open in Firefox, so those links were removed. 
Two recommended links were also added:
●	The book: Preservation in Digital Cartography: 
https://link.springer.com/book/10.1007/978-3-642-12733-5
●	Other available guidelines: 
https://github.com/DILCISBoard/CITS-Geospatial/wiki/Related-guidelines
