### ISSUE TITLE
GEO_11 Rationale Readability

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#47]
The current text could use a revision to improve readability

> This requirement is depends on the fact that because some organisations hold no geospatial records
> themselves uses GIS applications, based on web services from exclusively external sources. This requirement
> enables the preservation of the behaviour, structure and rendering examples alone – an IP with no data.

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/c2fbb368-5b22-4877-8571-74b4fe807e10)

e.g. This requirement is only SHOULD (rather than MUST) to enable preservation of GIS behaviour, structure and rendering for organisations that use GIS applications (based on web services from exclusively external sources) but do not hold their own geospatial records. Therefore, this enables an IP with no data.

**Comment by GregorZavrsnik** [comment]
The rationale text was changed to a more understandable version:
"This requirement is based on the fact that more and more data is distributed. Thereofore, some organizations do not maintain their own geospatial records but instead use GIS applications that rely solely on web services from external sources. This requirement ensures the preservation of the behavior, structure, and rendering examples without involving any data, essentially creating an Information Package with no data content."
