### ISSUE TITLE
GEO_15 Rationale - CRS Timestamp

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#48]
The CRS information should include both EPSG code and timestamp. As can be seen on the EPSG website https://epsg.org/crs_4326/WGS-84.html, the definitions are regularly updated:

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/405d812a-e0f8-4dfb-a713-8a282c1c37c5)

Please also remove the sessionkey from the URL in the footnote:

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/ecd267e9-9999-4ed5-b02a-e87d1b750495)

**Comment by GregorZavrsnik** [comment]
The following text was added to the GEO_15 Description in the Guideline_CITS_Geospatial_with_GIS document:
"If there are multiple versions of a CRS it is also important to include a timestamp or the valid version of the CRS reference. Often coordinate systems with the same EPSG code change over time.
Example: 
See an example of a full description of a CRS in the WKT Format in Figure 11 and a GML version, containing the Timestamp in the “RevisionDate” tag.

Additionally an example of a GML version, containing the timestamp in the RevisionDate tag, was added to the example of the GEO_38 Rationale.
