### ISSUE TITLE
GEO_30 Rationale - Data Access Timestamp

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#49]
The creation date and the time slider settings alone may not be sufficient to achieve the stated goal "reproduce an original digital information product" because the data provided by the referenced services can be changing as well. Therefore, the time stamp of when the services were accessed should be included as well. 

(If it is assumed that the IP creation date is equal to the timestamp of services access, this should be stated clearly in the text)

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/361b2898-6fdf-4186-88ec-9ec6ae4be138)

**Comment by GregorZavrsnik** [comment]
The following text was added to the end of the paragraph:
"However, it is recommended, that all data also includes a timestamp of its usage, since the data provided by the referenced services can be changing as well."
