### ISSUE TITLE
GEO_33 Rationale - Map Styling / SLD Limitations

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#50]
The rationale seems to assume that all styles can be represented by SLD. However, this is not true since SLD is rather limited and only covers basic rendering rules. The rationale should be extended to address this issue.

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/5e874b37-a87c-41f3-9afd-23c50e921e29)

**Comment by anitagraser** [comment]
SLD is insufficient to represent original cartographic styles. 

Map producing organizations are considering CSS or JSON for vector tiles instead.

**Comment by anitagraser** [comment]
The German GDI-DE https://wiki.gdi-de.org/display/Arch/Verzeichnis+GDI-DE+Standards is currently keeping an eye on the [OGC API-Styles](https://ogcapi.ogc.org/styles/) developments: 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/8150fe15-862c-4a0e-ae27-a59cbac7109d)

**Comment by anitagraser** [comment]
Ad vector tiles, for example, the Austrian basemap.at is being published in .vtpk (Vector Tile Package) format  at https://www.data.gv.at/katalog/de/dataset/basemap-at-verwaltungsgrundkarte-vektor-offline-osterreich 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/f8719973-88b1-4c41-9c4f-149b6f386754)

This includes the vector data as well as the styling, which can be used ([and even modified](https://anitagraser.com/2023/12/15/offline-vector-tile-package-vtpk-in-qgis/)) in open source GIS, such as QGIS:

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/b68f2aef-da0c-4360-aea8-c444e4be5a81)

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/68c02d7f-8d23-4041-9bb9-7ab01f214498)

**Comment by anitagraser** [comment]
Chen, Y. (2019). Archiving digital maps with GeoPackage and vector-tile dissemination [Diploma Thesis, Technische Universität Wien]. reposiTUm. https://doi.org/10.34726/hss.2019.60322

- https://cartographymaster.eu/wp-content/theses/2019_CHEN_Presentation.pdf 
- https://repositum.tuwien.at/handle/20.500.12708/7566

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/a573be1d-e639-4965-9af7-44eccdc5a87e)

**Comment by GregorZavrsnik** [comment]
The description of the GEO_33 Rationale was generalized, so that the SLD format can be seen just as an example, even though it is not the best one. Other standards are mentioned to give readers possibility to choose. 
We aim to develop this topic further in future, when more resources become available.
