### ISSUE TITLE
GEO_35 Rationale - Documentation & Source Code

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#51]
It is unclear why this rationale only recommends archiving user documentation instead of the actual GIS system source code (wherever available). 

The stated goal could be achieved more easily if the source code is preserved:

> The purpose of describing the initial GIS system used to create, manage or manipulate the preserved geospatial
> data in the Information Package is to be able to recreate a rendering tool and its functionality in the future.

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/9c0455bc-ed1c-4982-85a1-09d6f38d66b1)

**Comment by GregorZavrsnik** [comment]
In the Example section of the GEO_35, the text in bold was added to the list of documentation examples:
"This could be any existing manuals, articles on common practices or white papers describing the common methods for use, manipulation, analysis, application **and source code**, etc., of the geospatial dataset."
