### ISSUE TITLE
Data Catalog Vocabulary (DCAT) recommendation 

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#55]
Inspire is not sufficient for long-term archiving purposes. Furthermore, the Inspire community is more focused on providing up-to-date information than on archiving. 

DCAT provides a better / more comprehensive basis for describing spatial datasets for archival purposes: 
https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_spatial

**Comment by GregorZavrsnik** [comment]
Could you please elaborate on this claim? What specifically is lacking in the INSPIRE metadata, that you suggest that DCAT can? 

I would also comment, that in the CITS Geospatial Specification, the content of the recommended storage of INSPIRE metadata, does not cover the full documentation required, to document a geospatial dataset or environment in which it was used. The specification (along with its guidelines), supports multiple possibilities to document geospatial records and their usage. To allow the wide array of existing resources, we support the usage of written documentation, images, videos, audio recordings, and various types of machine-readable metadata types, from those based on ISO 19115, 19165-1, INSPIRE metadata, and also proprietary metadata, if the archive decides it suits their needs. 

On the other hand, I do agree, that DCAT (and its Geo version) is worth mentioning and be documented as a viable option for geodata managers, producers and archives to consider. So we will add this requirement to future changes list.

**Comment by GregorZavrsnik** [comment]
A mention of Data Catalogue vocabulary and its Geospatial version was added to the Guidelines document on the first page of the 3.5. Chapter (p. 75)
