### ISSUE TITLE
GeoTiff compression recommendations

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#57]
[Guideline_CITS_Geospatial_Appendix_2_v1.pdf](https://citsgeospatial.dilcis.eu/guideline/Guideline_CITS_Geospatial_Appendix_2_v1.pdf) gives some guidelines re compression

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/df59f12e-946e-4643-9093-584036531894)

It may be worth to explicitly warn readers to not use JPEG compression to avoid compression artifacts.

**Comment by GregorZavrsnik** [comment]
Thank you for the comment, recommendation exepted

**Comment by GregorZavrsnik** [comment]
The following text was added to the  D_5.1-2 Requirement of the Guideline_CITS_Geospatial_Appendix_2:

In a TIFF file lossy compressions like JPEG should be avoided. Especially if the exact value of pixels is important.
