### ISSUE TITLE
Figure 1 is not intuitive

### ISSUE THREAD

**Issue by marcingrudzien** [DILCISBoard/CITS-Geospatial#6]
Dataset shown in figure 1 is too abstract, especially for a non-expert reader.  Consider replacing it with for example map showing countries in Europe.

**Comment by GregorZavrsnik** [comment]
In the version 3.0 we moved the figure showing an example of a geospatial dataset into the Guidelines for CITS Geospatial 1.0. The Figure 1 in that document shows a map of countries in Europe.
