### ISSUE TITLE
Tables and figures in the document are not numbered

### ISSUE THREAD

**Issue by marcingrudzien** [DILCISBoard/CITS-Geospatial#7]
Tables and figures in the document are not numbered (table form page 16) or the numbers are not correct (listing 26 page 13).  It is a minor issue, but it has to be corrected.

**Comment by GregorZavrsnik** [comment]
In the CITS Geospatial v3.0 all the Figures (images) and Tables are now numbered. The document also contains a list of tables (on page 5).
